Login_User/urls.py
from django.urls import path, include
from Login_User.views import login, registrations, Profile,logout_view,Update_Profile,update_user, UpdateBlog, delete_blog

app_name="Login_User"
urlpatterns = [
    path("login/", login, name="login"),  
    path("registrations/", registrations, name="registrations"),  
    path("logout_view/", logout_view, name="logout_view"),  
    path('profile/<str:username>', Profile, name="Profile"),  
    path('Update_Profile/<str:username>', Update_Profile, name="Update_Profile"),  
    path('update_user/<str:username>', update_user, name="update_user"),
    # path('edit_blog/<pk>', EditBlog, name="EditBlog"),
    path('edit_blog/<pk>', UpdateBlog.as_view(), name="EditBlog"),
    path('delete_blog/<pk>', delete_blog, name="delete_blog"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('Articles.urls')),
    path("User/",include('Login_User.urls')),
]

Login_User/models.py
from ast import Pass
from django.db import models
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.urls import reverse_lazy,reverse


class UserProfile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    phone=models.CharField(max_length=15, null=True, blank=True)
    bio=models.CharField(max_length=150, null=True, blank=True)
    address=models.CharField(max_length=50, null=True, blank=True)


    def get_absulate_url(self):
        # return reverse_lazy('Login_User:Profile', args=[self.user.username])
        return reverse("Login_User:Profile", kwargs={'username':self.user.username})
    def __str__(self) -> str:
        return self.user.username +'-' +str(self.pk)

Login_User/views.py
from django.shortcuts import redirect, render, get_list_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from Login_User.models import UserProfile
from Articles.models import Blog, comment
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, ListView, View


def login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        valid_User=authenticate(request, username=username, password=password)

        if valid_User is not None:
            auth_login(request, valid_User)
            return redirect(reverse_lazy("Articles:Home"))
        else:
            contex={"message":"Wrong informations", "class":"alert alert-warning alert-dismissible fade show"}
            return render(request, 'Login_user/login.html', contex)

    return render(request, 'Login_User/login.html')


def registrations(request):
    if request.method=='POST':
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        phone=" "
        address=" "
        bio=f"I am {username}."

        check_email=User.objects.filter(email=email).first()

        if check_email:
            contex={"message":"User alrady exits", "class":"alert alert-warning alert-dismissible fade show"}
            return render(request, 'Login_user/registrations.html', contex)
        
        user=User.objects.create_user(username=username, email=email, password=password)
        profile=UserProfile(user=user,phone=phone, address=address, bio=bio)
        profile.save()

        valid_User=authenticate(request, username=username, password=password)

        if valid_User is not None:
            auth_login(request, valid_User)
            return redirect(reverse_lazy("Articles:Home"))
        else:
            return HttpResponse("Ragistrations fail")

    return render(request, 'Login_user/registrations.html')


def logout_view(request):
    logout(request)
    return redirect(reverse_lazy("Articles:Home"))


def Profile(request, username):
    user_info=get_list_or_404(User, username=username)
    posted_articles=Blog.objects.filter(author=request.user)
    
    if request.user.is_authenticated:
        current_user=request.user
        user_id=current_user.id
        user_profile_info=UserProfile.objects.get(user__pk=user_id)


    context={"user_info":user_info, "user_profile_info":user_profile_info, "posted_articles":posted_articles}
    return render(request, 'Login_user/profile.html',context)


def Update_Profile(request, username):
    user_info=get_list_or_404(User, username=username)
    if request.user.is_authenticated:
        current_user=request.user
        user_id=current_user.id
        user_profile_info=UserProfile.objects.get(user__pk=user_id)
        
    context={"user_info":user_info, "user_profile_info":user_profile_info}
    return render(request, 'Login_user/UpdateProfile.html',context)


def update_user(request,username):
    if request.user.is_authenticated:
        current_user=request.user
        user_id=current_user.id
        user_profile_info=UserProfile.objects.get(user__pk=user_id)
        user_profile_info_id=user_profile_info.id
        print(user_profile_info_id)

    if request.method=="POST":
        username=request.POST.get("username")
        phone=request.POST.get("phone")
        bio=request.POST.get("bio")
        address=request.POST.get("address")

        user=User.objects.filter(id=user_id).update(username=username)
        UserProfile.objects.filter(pk=user_profile_info_id).update(phone=phone, bio=bio, address=address)
        return HttpResponseRedirect(reverse('Login_User:Profile', kwargs={'username':username}))
    
    return render(request, 'Login_user/UpdateProfile.html')

# def EditBlog(request,pk):
#     post=Blog.objects.filter(pk=pk)
#     # print(post.title)

#     context={"post":post}
#     return render(request, 'Articles/edit_blog.html', context)


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model=Blog
    template_name='Articles/edit_blog.html'
    fields=('title','blog_content','blog_image')

    def get_success_url(self, **kwargs):
        return reverse_lazy("Articles:aticle_details", kwargs={'slug':self.object.slug})


def delete_blog(request,pk):
    post=Blog.objects.filter(pk=pk)

    for i in post:
        author=i.author

    user=request.user
    if author== user:
        post.delete()
        return HttpResponseRedirect(reverse('Login_User:Profile', kwargs={'username':user.username}))
    else:
        message="You can't delete this post. Because you are not author this post."
        return render(request, 'Login_user/profile.html', {"message":message})
        # return HttpResponseRedirect(reverse('Login_User:Profile', kwargs={'username':user.username}))

templates/Login_User/UpdateProfile.html
{% extends 'base.html' %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Login_User/css/updateprofile.css' %}">
{% endblock %}
{% block body%}
        <div class="container rounded bg-white mt-5 mb-5">
            <div class="row updateprofile">
                <div class="col-md-3 border-right">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                        <img class="rounded-circle mt-5" src="https://i.imgur.com/O1RmJXT.jpg" width="90">
                        <span class="font-weight-bold">{{user_info.username}}</span>
                        <span class="text-black-50">{{user_info.email}}</span>
                        <span>{{user_info.profile.country}}</span></div>
                </div>
                <div class="col-md-5 border-right">
                   <form action="{% url 'Login_User:update_user' username=request.user.username %}" method="post" >
                        {% csrf_token %} 
                        <!-- enctype="multipart/form-data" -->
                        <div class=" text-center">
                            <h3 class="text-center text-info pt-2">Edit Your Profile</h3>
                        </div>
                        <hr>
                        <div class="p-3">
                            <div class="row mt-2">
                                <div class="col-md-12">
                                    <label class="labels">User Name</label>
                                    <input name='username' type="text" class="form-control" placeholder="UserName" value="{{user.username}}">
                                </div>
                                <div class="col-md-12">
                                    <label class="labels">Phone</label>
                                    <input name='phone' type="text" class="form-control" placeholder="" value="{{user_profile_info.phone}}">
                                </div>
                                <div class="col-md-12">
                                    <label class="labels">Bio</label>
                                    <input name='bio' type="text" class="form-control" placeholder="" value="{{user_profile_info.bio}}">
                                </div>
                                <div class="col-md-12">
                                    <label class="labels">Location</label>
                                    <input name='address' type="text" class="form-control" placeholder="UserName" value="{{user_profile_info.address}}">
                                </div>
                            </div>
                            <div class="mt-5 text-center">
                                <input type="submit" class="btn btn-primary profile-button" value="save">
                            </div>
                        </div>
                   </form>
                </div>
                <div class="col-md-4">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center experience"><span>Edit Experience</span><span class="border px-3 p-1 add-experience"><i class="fa fa-plus"></i>&nbsp;Experience</span></div>
                        <div class="d-flex flex-row mt-3 exp-container"><img src="https://i.imgur.com/azSfBM3.png" width="45" height="45">
                            <div class="work-experience ml-1"><span class="font-weight-bold d-block">Senior UI/UX Designer</span><span class="d-block text-black-50 labels">Twitter Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
                        </div>
                        <hr>
                        <div class="d-flex flex-row mt-3 exp-container"><img src="https://img.icons8.com/color/100/000000/facebook.png" width="45" height="45">
                            <div class="work-experience ml-1"><span class="font-weight-bold d-block">Senior UI/UX Designer</span><span class="d-block text-black-50 labels">Facebook Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
                        </div>
                        <hr>
                        <div class="d-flex flex-row mt-3 exp-container"><img src="https://img.icons8.com/color/50/000000/google-logo.png" width="45" height="45">
                            <div class="work-experience ml-1"><span class="font-weight-bold d-block">UI/UX Designer</span><span class="d-block text-black-50 labels">Google Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
{% endblock %}

templates/Login_User/login.html
{% extends 'base.html'%}
{% block head %}
{% load static%}
<!-------------------------------- Bootstrap-icon link -------------------------------->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<!-------------------------------- CSS link -------------------------------->
<link rel="stylesheet" href="{% static 'Login_User/css/login.css'%}">
{% endblock %}

{% block body%}
<section>
  <div class="container-fluid h-custom mt-2">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid"
          alt="Sample image">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <form method="post" action="{% url 'Login_User:login'%}">
          {% csrf_token%}
          <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
            <p class="lead fw-normal mb-0 me-3">Sign in with</p>

            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="bi bi-facebook"></i>
            </button>

            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="bi bi-google"></i>
            </button>
          </div>

          <div class="divider d-flex align-items-center my-4">
            <p class="text-center fw-bold mx-3 mb-0">Or</p>
          </div>

          <div class="{{class}}" role="alert">
            <strong></strong> {{message}}.
          </div>
          <!-- username input -->
          <div class="form-outline mb-4">
            <input type="text" name="username" id="form3Example3" class="form-control form-control-lg"
              placeholder="Enter a valid username" autofocus />
          </div>

          <!-- Password input -->
          <div class="form-outline mb-3">
            <input type="password" name="password" id="form3Example4" class="form-control form-control-lg"
              placeholder="Enter password" />
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <!-- Checkbox -->
            <div class="form-check mb-0">
              <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
              <label class="form-check-label" for="form2Example3">
                Remember me
              </label>
            </div>
            <a href="#!" class="text-body">Forgot password?</a>
          </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <input type="submit" class="btn btn-primary btn-lg" style="padding-left: 2.5rem; padding-right: 2.5rem;"
              value="Login">
            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a
                href="{% url 'Login_User:registrations' %}" class="link-danger">Register</a></p>
          </div>

        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/Login_User/profile.html
{% extends 'base.html'%}
{% block head %}
{% load static%}
<!-------------------------------- Bootstrap-icon link -------------------------------->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<!-------------------------------- CSS link -------------------------------->
<link rel="stylesheet" href="{% static 'Login_User/css/profile.css'%}">
<link rel="stylesheet" href="{% static 'common.css'%}">
{% endblock %}
{% block body%}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row d-flex justify-content-center">
            <div class="col-xl-12 col-md-12 ">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25"> <img src="https://img.icons8.com/bubbles/100/000000/user.png"
                                        class="img-radius" alt="User-Profile-Image"> </div>
                                <h6 class="f-w-600">
                                    {{user.username}}</h6>
                                <p>{{user_profile_info.bio}}</p>
                                <div class="pt-3">
                                    <a class="myButton btn-primary "
                                        href="{% url 'Login_User:Update_Profile' username=request.user.username %}">Update
                                        Profile</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">{{message}}</h6>
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Personal Information</h6>
                                <div class="row">
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400">{{user.email}}</h6>
                                    </div>
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Phone</p>
                                        <h6 class="text-muted f-w-400">{{user_profile_info.phone}}</h6>
                                    </div>
                                    <div class="col-sm-4">
                                        <p class="m-b-10 f-w-600">Location</p>
                                        <p class="">{{user_profile_info.address}}</p>
                                    </div>
                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Your Post Informations.</h6>
                                <div class="row">
                                    <div class="col-sm-12">
                                        {% for post in posted_articles %}
                                        <li>
                                            <a href="{{post.get_absulate_url}}">
                                                {{post.title}}
                                            </a>
                                            ----------------------
                                            <i class="fas fa-thumbs-up"></i>{{post.blog_like.count}}
                                            <i class="fas fa-comment"></i>{{post.blog_comment.count}}
                                            <br>
                                            <a href="{% url 'Login_User:EditBlog' pk=post.pk %}" class="btn btn-success mt-3">Edit</a>
                                            <a href="{% url 'Login_User:delete_blog' pk=post.pk %}" class="btn btn-danger mt-3">delete</a>
                                            <hr>
                                        </li>
                                        {% endfor %}
                                    </div>
                                    <!-- <div class="col-sm-6">
                                        
                                    </div> -->
                                </div>
                                <ul class="social-link list-unstyled m-t-40 m-b-10">
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
                                            data-original-title="facebook" data-abc="true"><i
                                                class="mdi mdi-facebook feather icon-facebook facebook"
                                                aria-hidden="true"></i></a></li>
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
                                            data-original-title="twitter" data-abc="true"><i
                                                class="mdi mdi-twitter feather icon-twitter twitter"
                                                aria-hidden="true"></i></a></li>
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
                                            data-original-title="instagram" data-abc="true"><i
                                                class="mdi mdi-instagram feather icon-instagram instagram"
                                                aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

templates/Login_User/registrations.html
{% extends 'base.html'%}
{% block head %}
{% load static%}
<!-------------------------------- Bootstrap-icon link -------------------------------->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<!-------------------------------- CSS link -------------------------------->
<link rel="stylesheet" href="{% static 'Login_User/css/login.css'%}">
{% endblock %}

{% block body%}
<section>
    <div class="container-fluid h-custom mt-2">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="{% static 'Login_user/images/registrations.png'%}" class="img-fluid"
            alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1 mt-5">
          <form method="post" action="{% url 'Login_User:registrations'%}">
            {% csrf_token %}
            <div class="{{class}}" role="alert">
              <strong></strong> {{message}}.
            </div>
            <!-- user name input -->
            <div class="form-outline mb-4">
              <input type="text" name="username" id="form3Example3" class="form-control form-control-lg"
                placeholder="Enter user name" />
            </div>
             <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" name="email" id="form3Example3" class="form-control form-control-lg"
                placeholder="Enter a valid email address" />
            </div>
  
            <!-- Password input -->
            <div class="form-outline mb-3">
              <input type="password" name="password" id="form3Example4" class="form-control form-control-lg"
                placeholder="Enter password" />
            </div>
  
            <div class="text-center text-lg-start mt-4 pt-2">
              <input type="submit" class="btn btn-primary btn-lg"
              style="padding-left: 2.5rem; padding-right: 2.5rem;" value="Registrations">
              <p class="small fw-bold mt-2 pt-1 mb-0 mt-5">I have an account? <a href="{% url 'Login_User:login' %}"
                  class="link-danger">Login</a></p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}