Articles/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Articles.views import Home, CreateBlog, aticle_details, liked, unlike

app_name='Articles'
urlpatterns = [
    path("", Home, name="Home"),
    path("create_blog/", CreateBlog.as_view(), name="Create_Blog"),
    path("aticle_details/<str:slug>/", aticle_details, name="aticle_details"),
    path("liked/<int:pk>/", liked, name="liked"),
    path("unlike/<int:pk>/", unlike, name="unlike"),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('Articles.urls')),
    path("User/",include('Login_User.urls')),
]

Articles/models.py
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
from django.urls import reverse_lazy

# Create your models here.

class Blog(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_author")
    title=models.CharField(max_length=80)
    slug=models.SlugField(max_length=80, unique=True)
    blog_content=models.TextField(verbose_name="What is on your mind?")
    blog_image=models.ImageField(upload_to="Articles/", verbose_name="Image")
    publish_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)
    published=models.BooleanField(default=True)

    def get_absulate_url(self):
        return reverse_lazy('Articles:aticle_details', args=[self.slug])
        
    class Meta:
        ordering = ['-publish_date']

    def __str__(self) -> str:
        return self.title

class comment(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_comment")
    blog=models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="blog_comment")
    comment=models.TextField()
    publish_date=models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-publish_date',]
        
    def __str__(self) -> str:
        return self.comment


class like(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_like")
    blog=models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="blog_like")

Articles/views.py
import imp
from multiprocessing import context
from django.http import HttpResponse, HttpResponseRedirect

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from Login_User.models import UserProfile
from Articles.models import Blog, comment, like
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, ListView, View
import uuid


# Create your views here.
# class Home(ListView):
#     context_object_name='blogs'
#     model=Blog
#     template_name='Article/blog_list.html'
def Home(request):
    blogs=Blog.objects.all()
    blog_titles=Blog.objects.filter(published=True).order_by("-published")[:5]
    latest_blog=Blog.objects.filter(published=True).order_by("-published")
    
    context={"blogs":blogs,"blog_titles":blog_titles, "latest_blog":latest_blog}
    return render(request, 'Articles/blog_list.html', context)

class CreateBlog(LoginRequiredMixin, CreateView):
    model=Blog
    template_name='Articles/create_blog.html'
    fields=('title','blog_content','blog_image')

    def form_valid(self, form):
        form_obj=form.save(commit=False)
        form_obj.author=self.request.user
        title=form_obj.title
        form_obj.slug=title.replace(" ", "-") +"-"+ str(uuid.uuid4())
        form_obj.save()
        return redirect(reverse_lazy('Articles:Home'))


@login_required
def aticle_details(request,slug):
    blog=Blog.objects.get(slug=slug)
    blog_author=blog.author
    user_id=blog_author.id
    user_profile_info=UserProfile.objects.get(user__pk=user_id)


    if request.method=='POST':
        message=request.POST.get("message")
        blog=blog
        user=request.user
        print(user)
        comments=comment(user=user,blog=blog,comment=message)
        comments.save()
        return HttpResponseRedirect(reverse("Articles:aticle_details", kwargs={'slug':slug}))
        
    comments=comment.objects.filter(blog=blog)
    already_like=like.objects.filter(blog=blog, user=request.user)
    if already_like:
        liked=True
    else:
        liked=False
        

    context={"blog":blog, "comments":comments, "liked":liked,"user_profile_info":user_profile_info}
    return render(request, 'Articles/articles_details.html', context)


@login_required
def liked(request,pk):
    blog=Blog.objects.get(pk=pk)
    user=request.user
    already_liked=like.objects.filter(user=user, blog=blog)
    print(already_liked)
    if not already_liked:
        like_post=like(user=user, blog=blog)
        like_post.save()

    return HttpResponseRedirect(reverse("Articles:aticle_details", kwargs={'slug':blog.slug}))


@login_required
def unlike(request,pk):
    blog=Blog.objects.get(pk=pk)
    user=request.user
    already_liked=like.objects.filter(user=user, blog=blog)
    already_liked.delete()
    return HttpResponseRedirect(reverse("Articles:aticle_details", kwargs={'slug':blog.slug}))

templates/Articles/articles_details.html
{% extends 'base.html'%}

{% block head%}
{% load static %}
<link rel="stylesheet" href="{% static 'Articles/css/articalepage.css'%}">
{% endblock %}

{% block body %}
    <div class="blog-single gray-bg">
    <div class="container-fluid">
        <div class="row align-items-start">
            <div class="col-lg-9 m-15px-tb">
                <article class="article">
                    <div class="article-img">
                        <img src="/media/{{blog.blog_image}}" alt="article-image">
                    </div>
                    <div class="article-title">
                        <!-- <h6><a href="#">{{blog.catagory}}</a></h6> -->
                        <h2>{{blog.title}}</h2>
                        <div class="media">
                            <div class="avatar">
                                <img src="https://bootdey.com/img/Content/avatar/avatar1.png" title="" alt="">
                            </div>
                            <div class="media-body">
                                <label>
                                    <a href="{{user_profile_info.get_absulate_url}}">
                                        {{user_profile_info}}
                                        {{blog.author}}
                                    </a>
                                </label>
                                <span>{{blog.publish_date}}</span>
                            </div>
                        </div>
                    </div>
                    <div class="article-content">
                        <p>{{blog.blog_content|linebreaks}}</p>
                    
                    </div>
                    <div class="nav tag-cloud">
                        <a href="#">tag</a>
                        <a href="#">Travel</a>
                        <a href="#">Web Design</a>
                        <a href="#">Marketing</a>
                        <a href="#">Research</a>
                        <a href="#">Managment</a>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-lg-6 like">
                            {% if not liked %}
                            <a href="{% url 'Articles:liked' pk=blog.pk%}">
                                <i class="fas fa-thumbs-up"></i>
                            </a>
                            {% else %}
                            <a href="{% url 'Articles:unlike' pk=blog.pk%}">
                                <i class="fas fa-thumbs-down"></i>
                            </a>
                            {% endif %}
                        </div>
                        <div class="col-lg-6">
                            <div class="float-end">
                                <i class="fas fa-thumbs-up"></i>{{blog.blog_like.count}} &nbsp; 
                                <i class="fas fa-comment"></i>
                                {{blog.blog_comment.count}}
                            </div>
                            
                        </div>
                    </div>
                </article>
                <div class="row me-5 ms-5">
                    {% for i in comments %}
                    <div class="article-comment mb-3">
                        <div class="col-lg-6">
                            {{i.user}}
                        </div>
                        <div class="col-lg-6">
                            {{i.comment}}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="contact-form article-comment">
                    <h4>Leave a Reply</h4>
                    <form action="{% url 'Articles:aticle_details' slug=blog.slug%}" id="contact-form" method="POST">
                        {% csrf_token%}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <textarea name="message" id="message" placeholder="Your message *" rows="4" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="send">
                                    <button class="px-btn theme"><span>Submit</span> <i class="arrow"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-3 m-15px-tb blog-aside">
                <!-- Author -->
                <div class="widget widget-author">
                    <div class="widget-title">
                        <h3>Author</h3>
                    </div>
                    <div class="widget-body">
                        <div class="media align-items-center d-flex flex-row">
                            <div class="avatar">
                                <img src="https://bootdey.com/img/Content/avatar/avatar6.png" title="" alt="">
                            </div>
                            <div class="media-body">
                                <h6>Hello, I'm<br>{{blog.author}}</h6>
                            </div>
                        </div>
                        <p>{{current_user.bio}} ki</p>
                    </div>
                </div>
                <!-- End Author -->
                <!-- Trending Post -->
                <div class="widget widget-post">
                    <div class="widget-title">
                        <h3>Trending Now</h3>
                    </div>
                    <div class="widget-body">

                    </div>
                </div>
                <!-- End Trending Post -->
                <!-- Latest Post -->
                <div class="widget widget-latest-post">
                    <div class="widget-title">
                        <h3>Latest Post</h3>
                    </div>
                    <div class="widget-body">
                        <div class="latest-post-aside media">
                            <div class="lpa-left media-body">
                                <div class="lpa-title">
                                    <h5><a href="#">Prevent 75% of visitors from google analytics</a></h5>
                                </div>
                                <div class="lpa-meta">
                                    <a class="name" href="#">
                                        Rachel Roth
                                    </a>
                                    <a class="date" href="#">
                                        26 FEB 2020
                                    </a>
                                </div>
                            </div>
                            <div class="lpa-right">
                                <a href="#">
                                    <img src="https://via.placeholder.com/400x200/FFB6C1/000000" title="" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="latest-post-aside media">
                            <div class="lpa-left media-body">
                                <div class="lpa-title">
                                    <h5><a href="#">Prevent 75% of visitors from google analytics</a></h5>
                                </div>
                                <div class="lpa-meta">
                                    <a class="name" href="#">
                                        Rachel Roth
                                    </a>
                                    <a class="date" href="#">
                                        26 FEB 2020
                                    </a>
                                </div>
                            </div>
                            <div class="lpa-right">
                                <a href="#">
                                    <img src="https://via.placeholder.com/400x200/FFB6C1/000000" title="" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="latest-post-aside media">
                            <div class="lpa-left media-body">
                                <div class="lpa-title">
                                    <h5><a href="#">Prevent 75% of visitors from google analytics</a></h5>
                                </div>
                                <div class="lpa-meta">
                                    <a class="name" href="#">
                                        Rachel Roth
                                    </a>
                                    <a class="date" href="#">
                                        26 FEB 2020
                                    </a>
                                </div>
                            </div>
                            <div class="lpa-right">
                                <a href="#">
                                    <img src="https://via.placeholder.com/400x200/FFB6C1/000000" title="" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Latest Post -->
                <!-- widget Tags -->
                <div class="widget widget-tags">
                    <div class="widget-title">
                        <h3>Latest Tags</h3>
                    </div>
                    <div class="widget-body">
                        <div class="nav tag-cloud">
                            <a href="#">Design</a>
                            <a href="#">Development</a>
                            <a href="#">Travel</a>
                            <a href="#">Web Design</a>
                            <a href="#">Marketing</a>
                            <a href="#">Research</a>
                            <a href="#">Managment</a>
                        </div>
                    </div>
                </div>
                <!-- End widget Tags -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/Articles/blog_list.html
{% extends 'base.html'%} {% block head%}
<!-------------------------------- Bootstrap-icon link -------------------------------->
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" />
<link rel="stylesheet" href="{% static 'articles/css/style.css' %}">
{% endblock%} {% block body%}

<!-- Page content-->
<div class="container-fluid">
    <div class="row mt-5">
        <!-- Blog entries-->
        <div class="col-lg-9 col-md-9 col-sm-9">
            <!-- Featured blog post-->
            <div class="card mb-4">
                <a class="card_image" href="#!"
                    ><img class="card-img-top" src="media/{{latest_blog.0.blog_image}}" alt="..."/>
                </a>
                <div class="card-body">
                    <div class="small text-muted">January 1, 2021</div>
                    <a href="{{latest_blog.0.get_absulate_url}}">
                        <h2  class="card-title">{{latest_blog.0.title}}</h2>
                    </a>
                    <p class="card-text">
                        {{latest_blog.0.blog_content|truncatewords:30}}
                    </p>
                    <a class="btn btn-primary" href="{{latest_blog.0.get_absulate_url}}">Read more →</a>
                </div>
            </div>
            <!-- Nested row for non-featured blog posts-->
            <div class="row">
                {% for blog in blogs%}
                <div class="col-lg-6">
                    <!-- Blog post-->
                    <div class="card mb-4">
                        <a class="card_image" href="#!">
                            <img class="card-img-top" src="media/{{blog.blog_image}}" alt="{{blog.blog_image}}" title="{{blog}}"
                            />
                        </a>
                        <div class="card-body">
                            <div class="small text-muted">{{blog.publish_date}}</div>
                            <a href="{{blog.get_absulate_url}}">
                                <h2 class="card-title h4">{{blog.title.title|truncatewords:5}}</h2>
                            </a>
                            <p class="card-text">{{blog.blog_content|truncatewords:30}}</p>
                            <a class="btn btn-primary" href="{{blog.get_absulate_url}}">Read more →</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- Pagination-->
            <nav aria-label="Pagination">
                <hr class="my-0" />
                <ul class="pagination justify-content-center my-4">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a>
                    </li>
                    <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
                    <li class="page-item"><a class="page-link" href="#!">2</a></li>
                    <li class="page-item"><a class="page-link" href="#!">3</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                    <li class="page-item"><a class="page-link" href="#!">15</a></li>
                    <li class="page-item"><a class="page-link" href="#!">Older</a></li>
                </ul>
            </nav>
        </div>
        <!-- Side widgets-->
        <div class="col-lg-3 col-md-3 col-sm-3">
            <div class="mb-5 title_text">
                {% for title in blog_titles %}
                <li>
                    <a href="{{title.get_absulate_url}}"> {{title.title|truncatewords:10}} </a>
                </li>
                <hr />
                {% endfor %}
            </div>
            <hr style="color: brown; height: 3px" />
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input
                            class="form-control"
                            type="text"
                            placeholder="Enter search term..."
                            aria-label="Enter search term..."
                            aria-describedby="button-search"
                        />
                        <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                    </div>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#!">Web Design</a></li>
                                <li><a href="#!">HTML</a></li>
                                <li><a href="#!">Freebies</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#!">JavaScript</a></li>
                                <li><a href="#!">CSS</a></li>
                                <li><a href="#!">Tutorials</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4">
                <div class="card-header">Side Widget</div>
                <div class="card-body">
                    You can put anything you want inside of these side widgets. They are easy to use, and feature the
                    Bootstrap 5 card component!
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

templates/Articles/create_blog.html
{% extends 'base.html'%}
{% load crispy_forms_tags%}
{% block head%}
{% endblock%}

{% block body%}

<div class="container">
    <h1>Write your post</h1>
    <div class="row">
        <div class="col-lg-12">
            <form method="POST" enctype="multipart/form-data">
                {{form|crispy}}
                {% csrf_token %}
                <input class=" btn btn-success mt-3" type="submit" value="Publish">
            </form>
        </div>
    </div>
</div>
{% endblock%}

templates/Articles/edit_blog.html
{% extends 'base.html'%}
{% load crispy_forms_tags%}
{% block head%}
{% endblock%}

{% block body%}

<div class="container">
    <h1>Edit your post</h1>
    <div class="row">
        <div class="col-lg-12">
            {% if blog.author == request.user %}
            <form method="POST" enctype="multipart/form-data">
                {{form|crispy}}
                {% csrf_token %}
                <input class=" btn btn-success mt-3" type="submit" value="Update">
            </form>
            {% else %}
            <p>You are not able to edit this blog</p>
            <p>This blog autor is Mr.{{blog.author}}</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock%}