Articles/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Articles.views import Home, CreateBlog, aticle_details, liked, unlike

app_name='Articles'
urlpatterns = [
    path("", Home, name="Home"),
    path("create_blog/", CreateBlog.as_view(), name="Create_Blog"),
    path("aticle_details/<str:slug>/", aticle_details, name="aticle_details"),
    path("liked/<int:pk>/", liked, name="liked"),
    path("unlike/<int:pk>/", unlike, name="unlike"),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Login_User/urls.py
from django.urls import path, include
from Login_User.views import login, registrations, Profile,logout_view,Update_Profile,update_user, UpdateBlog, delete_blog

app_name="Login_User"
urlpatterns = [
    path("login/", login, name="login"),  
    path("registrations/", registrations, name="registrations"),  
    path("logout_view/", logout_view, name="logout_view"),  
    path('profile/<str:username>', Profile, name="Profile"),  
    path('Update_Profile/<str:username>', Update_Profile, name="Update_Profile"),  
    path('update_user/<str:username>', update_user, name="update_user"),
    # path('edit_blog/<pk>', EditBlog, name="EditBlog"),
    path('edit_blog/<pk>', UpdateBlog.as_view(), name="EditBlog"),
    path('delete_blog/<pk>', delete_blog, name="delete_blog"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('Articles.urls')),
    path("User/",include('Login_User.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{%block title%}Home{%endblock%}</title>
        <!--------------------------- fontawesome font  --------------------------->
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
        <!--------------------------- Bootstrap  --------------------------->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
        />
        {% block head %} {% endblock %}
        <style>
            .dropdown:hover .dropdown-menu {
                display: block;
            }
            .dropdown-menu {
                margin: 7px;
                margin-left: -48px;
                background-color: #343a40;
            }
            .dropdown-menu[data-bs-popper] {
                top: 100%;
                left: 0px;
                margin-top: 7px;
            }
        </style>
    </head>
    <body class="body">
        <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-info ps-5 pe-5">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Motalib Blog</a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarTogglerDemo02"
                    aria-controls="navbarTogglerDemo02"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" href="/">Home</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a
                                class="nav-link dropdown-toggle"
                                href="#"
                                id="navbarDarkDropdownMenuLink"
                                role="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                            >
                                {% load static%}
                                <img
                                    src="{% static 'profile-img.png'%}"
                                    alt="Profile"
                                    style="height: 30px; width: 30px; border-radius: 50%"
                                />
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li>
                                    <a
                                        class="dropdown-item"
                                        href="{% url 'Login_User:Profile' username=request.user.username %}"
                                        >Profile</a
                                    >
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'Articles:Create_Blog'  %}">Write Blog</a>
                                </li>
                                <hr />
                                <li>
                                    <a class="dropdown-item" href="{% url 'Login_User:logout_view' %}">logout</a>
                                </li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'Login_User:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Login_User:registrations' %}">Registrations</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block body %} 
        {% endblock%}


        <footer class="text-center text-lg-start text-white mt-5" style="background-color: #45526e">
            <!-- Grid container -->
            <div class="container p-4 pb-0">
                <!-- Section: Links -->
                <section class="">
                    <!--Grid row-->
                    <div class="row">
                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                            <h6 class="text-uppercase mb-4 font-weight-bold">Company name</h6>
                            <p>
                                Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit
                                amet, consectetur adipisicing elit.
                            </p>
                        </div>
                        <!-- Grid column -->

                        <hr class="w-100 clearfix d-md-none" />

                        <!-- Grid column -->
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                            <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
                            <p>
                                <a class="text-white">MDBootstrap</a>
                            </p>
                            <p>
                                <a class="text-white">MDWordPress</a>
                            </p>
                            <p>
                                <a class="text-white">BrandFlow</a>
                            </p>
                            <p>
                                <a class="text-white">Bootstrap Angular</a>
                            </p>
                        </div>
                        <!-- Grid column -->

                        <hr class="w-100 clearfix d-md-none" />

                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                            <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
                            <p>
                                <a class="text-white">Your Account</a>
                            </p>
                            <p>
                                <a class="text-white">Become an Affiliate</a>
                            </p>
                            <p>
                                <a class="text-white">Shipping Rates</a>
                            </p>
                            <p>
                                <a class="text-white">Help</a>
                            </p>
                        </div>

                        <!-- Grid column -->
                        <hr class="w-100 clearfix d-md-none" />

                        <!-- Grid column -->
                        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
                            <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
                            <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
                            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
                            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
                        </div>
                        <!-- Grid column -->
                    </div>
                    <!--Grid row-->
                </section>
                <!-- Section: Links -->

                <hr class="my-3" />

                <!-- Section: Copyright -->
                <section class="p-3 pt-0">
                    <div class="row d-flex align-items-center">
                        <!-- Grid column -->
                        <div class="col-md-7 col-lg-8 text-center text-md-start">
                            <!-- Copyright -->
                            <div class="p-3">
                                © 2020 Copyright:
                                <a class="text-white" href="https://motalibhossain.github.io/portfolio/">TechBlog</a>
                            </div>
                            <!-- Copyright -->
                        </div>
                        <!-- Grid column -->

                        <!-- Grid column -->
                        <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
                            <!-- Facebook -->
                            <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"
                                ><i class="bi bi-facebook"></i>
                            </a>

                            <!-- Twitter -->
                            <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"
                                ><i class="bi bi-google"></i></a>

                            <!-- Google -->
                            <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"
                                ><i class="bi bi-google"></i></a>

                            <!-- Instagram -->
                            <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"
                                ><i class="fab fa-instagram"></i></a>
                        </div>
                        <!-- Grid column -->
                    </div>
                </section>
                <!-- Section: Copyright -->
            </div>
            <!-- Grid container -->
        </footer>
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"
        ></script>
    </body>
</html>